version: '3.9'

services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./build/server
      dockerfile: server.Dockerfile
    command: ./app/server -p 80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo
    depends_on:
      - postgres
  
  proxy-server:
    container_name: proxy-server
    build:
      context: ./build/proxy
      dockerfile: proxy.Dockerfile
    command: ./app/proxy -p 80 -e grpc-server:80
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - grpc-server

  postgres:
    image: 'postgres:15.2'
    restart: always
    deploy:
      mode: global
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'todo'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
