version: '3.9'

services:
  grpc-server:
    container_name: grpc-server
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    command: ./app/server -p 80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=todo
      - DB_SSLMODE=disable
      - DB_TIMEZONE=UTC
    depends_on:
      - postgres
      - rabbitmq

  proxy-server:
    container_name: proxy-server
    build:
      context: .
      dockerfile: ./build/proxy/Dockerfile
    command: ./app/proxy -p 80 -e grpc-server:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - grpc-server

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    restart: always
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    container_name: postgres
    image: 'postgres:15.2'
    restart: always
    deploy:
      mode: replicas
      replicas: 1
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'todo'
    volumes:
      - ./db/data/postgres/:/var/lib/postgresql/data/
      - ./db/todo/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.11.13-management'
    restart: always
    deploy:
      mode: replicas
      replicas: 1
    ports:
      - 5672:5672
      - 15672:15672