// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package todo

import (
	"time"
)

type Todo struct {
	ID        string
	Content   string
	Priority  int32
	IsDone    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
